name: release

on:
  push:
    branches:
      - guru-packages

# concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: yarn && ls -la

      - name: Publish to github registry
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
